### ISSUE TITLE
inference demo error 

### ISSUE THREAD

**Issue by ahdxwg** [mit-han-lab/tinyengine#44] opened 2023-02-03 08:22 UTC
![image](https://user-images.githubusercontent.com/115546189/216548281-1e93de19-da81-4f5d-87e2-3f2cee7bb1e5.png)
When I followed the steps to build, there were these errors. Please help to solve them. Thank you very much

**Comment by meenchen** [comment] 2023-02-08 17:36
Hi @ahdxwg,

From the error logs, it looks like something is wrong with the path when you compile the project. Could you try to move the workspace somewhere else? (e.g., with English characters)

**Comment by ahdxwg** [comment] 2023-02-09 02:40
Thank you very much. I have solved the problem.

**Comment by meenchen** [comment] 2023-02-09 18:50
Glad to hear the problem is solved. I will close this issue then.

**Closed by meenchen** 2023-02-09 18:50 UTC
