### ISSUE TITLE
blank screen 

### ISSUE THREAD

**Issue by jonathan-ko** [mit-han-lab/tinyengine#14] opened 2022-11-06 07:21 UTC
Hi, I built the TinyEngine tutorial with zero errors. Then, after the download, the screen goes black immediately. No errors are mentioned. No warnings either. Any thoughts or advice?

![image](https://user-images.githubusercontent.com/6279413/200159039-225f2a5f-b79b-462d-89ee-7193303791c1.png)

**Comment by liuruiqi0520** [comment] 2022-11-07 07:14
I had a similar problem

**Comment by RaymondWang0** [comment] 2022-11-07 14:37
Hi @jonathan-ko and @liuruiqi0520, here are the debugging suggestions for your problems:
1) Please check whether you download the correct version (1.5.0) of STM32CubeIDE for the tutorial.
2) Please check whether you have the [same equipment](https://github.com/mit-han-lab/tinyengine/tree/master/tutorial#equipments) as ours.
3) Please check whether your PIN connection between Arducam and the board is correct ([Step 4 in the tutorial](https://github.com/mit-han-lab/tinyengine/tree/master/tutorial#detailed-instruction)).

**Comment by jonathan-ko** [comment] 2022-11-12 18:20
Thank you "download the correct version (1.5.0)" was my problem -- I downloaded the newest 1.10 -- warning to others.

**Comment by tonylins** [comment] 2022-11-14 17:29
I will close the issue since the problem is solved. Feel free to reopen.

**Closed by tonylins** 2022-11-14 17:29 UTC

**Comment by liuruiqi0520** [comment] 2022-12-02 04:19
Hello! Your answer perfectly solves my problem. I impressed by your excellent work in the field of TinyML and studied the source code of MCUNet and Once-for-all, But when I try to replicate TinyNAS with the method in the Once-for-all, I can't find the pre training weight of the supernet used in MCUNet, could you please release the pre training weight? It would be very helpful for my next work and I would greatly appreciate if you could reply me.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mit-han-lab/tinyengine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 晚上10:38
***@***.***&gt;;
抄送:&nbsp;"( /。\ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mit-han-lab/tinyengine] blank screen  (Issue #14)





 
Hi @jonathan-ko and @liuruiqi0520, here are the debugging suggestions for your problems:
  
Please check whether you download the correct version (1.5.0) of STM32CubeIDE for the tutorial.
 
Please check whether you have the same equipment as ours.
 
Please check whether your PIN connection between Arducam and the board is correct (Step 4 in the tutorial).
